apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    example: "true"
  name: lovely-octopus-test
  namespace: argocd
spec:
  arguments:
    parameters:
    - name: message
      value: hello argo
  entrypoint: argosay
  podGC:
    strategy: OnPodCompletion
  templates:
  - container:
      args:
      - echo
      - '{{inputs.parameters.message}}'
      command:
      - /argosay
      image: argoproj/argosay:v2
      name: main
      resources: {}
    inputs:
      parameters:
      - name: message
        value: '{{workflow.parameters.message}}'
    metadata: {}
    name: argosay
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  workflowMetadata:
    labels:
      example: "true"

